import {
  Loader2,
  Phone,
  MessageCircle,
  Shield,
  Clock,
  Users,
  Smartphone,
  Eye,
  EyeOff,
  ArrowRight,
  ArrowLeft,
  Check,
  X,
  AlertCircle,
  Home,
  User,
  Settings,
  LogOut,
  Bell,
  Search,
  Filter,
  Heart,
  Star,
  MapPin,
  Calendar,
  Upload,
  Download,
  Edit,
  Trash2,
  Plus,
  Minus,
  MoreVertical,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  List,
  Package,
  Inbox,
  FileText,
  RefreshCw,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  phone: Phone,
  messageCircle: MessageCircle,
  shield: Shield,
  clock: Clock,
  users: Users,
  smartphone: Smartphone,
  eye: Eye,
  eyeOff: EyeOff,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  x: X,
  alertCircle: AlertCircle,
  home: Home,
  user: User,
  settings: Settings,
  logOut: LogOut,
  bell: Bell,
  search: Search,
  filter: Filter,
  heart: Heart,
  star: Star,
  mapPin: MapPin,
  calendar: Calendar,
  upload: Upload,
  download: Download,
  edit: Edit,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  moreVertical: MoreVertical,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
  list: List,
  package: Package,
  inbox: Inbox,
  fileText: FileText,
  refresh: RefreshCw,
} 